let dia, mes, year, hora, minutos, d = new Date();
dia = (d.getDate()).toString();
mes = (d.getMonth()+1).toString();
year = d.getFullYear();
hora = (d.getHours()).toString();
minutos = (d.getMinutes()).toString();
if(dia.length < 2) dia = `0${dia}`;
if(mes.length < 2) mes = `0${mes}`;
if(hora.length < 2) hora = `0${hora}`;
if(minutos.length < 2) minutos = `0${minutos}`;
export {dia, mes, year, hora, minutos};